variable "profile" {}
variable "region" {}
variable "project-name" {}
variable "ami" {}
variable "cidr" {}
variable "public-cidr" {}
variable "private-cidr" {}
variable "az" {}
variable "domain_name" {}
variable "domain_name2" {}