apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest-api-app
  template:
    metadata:
      labels:
        app: rest-api-app
    spec:
      containers:
        - name: rest-api-app
          image: cloudhight/rest-api-app:lastest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: rest-api-app-service
spec:
  selector:
    app: rest-api-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer