apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  namespace: my-dev
  labels:
    app: flaskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
        - name: flaskapp
          image: eamanze/flask-app:5
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app:5
  namespace: my-dev
spec:
  type: NodePort
  selector:
    app: flaskapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001